/*
 * Copyright 2015 Igor Maznitsa.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.igormaznitsa.nbmindmap.model;

import java.io.IOException;
import java.io.Reader;
import java.io.Serializable;
import java.io.Writer;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.apache.commons.io.IOUtils;

public final class MindMap implements Serializable, Constants {

  private static final long serialVersionUID = 5929181596778047354L;

  private final MindMapTopic mainTopic;
  private final Lock locker = new ReentrantLock();
  private final Map<String, String> attributes = new HashMap<String, String>();
  private static final Pattern PATTERN_ATTRIBUTES = Pattern.compile("^\\s*\\>\\s*(.+)$");
  private static final Pattern PATTERN_ATTRIBUTE = Pattern.compile("[,]?\\s*([\\S]+?)\\s*=\\s*\\\"(.*?)\\\"");

  public MindMap() {
    this.mainTopic = new MindMapTopic(this, null, "");
  }

  public MindMap(final Reader reader) throws IOException {
    final StringBuilder lineBuffer = new StringBuilder();
    while (true) {
      final int chr = reader.read();
      if (chr < 0) {
        throw new IllegalArgumentException("It is not Mind Map");
      }
      if (chr == '\n') {
        final String line = lineBuffer.toString().trim();
        if (Utils.onlyFromChar(line, '-')) {
          break;
        }
        if (line.startsWith(">")) {
          fillMapByAttributes(line, this.attributes);
        }
        lineBuffer.setLength(0);
      }
      else {
        lineBuffer.append((char) chr);
      }
    }
    lineBuffer.trimToSize();

    final String str = IOUtils.toString(reader);
    this.mainTopic = MindMapTopic.parse(this, str);
  }

  public String getAttribute(final String name) {
    return this.attributes.get(name);
  }

  public void setAttribute(final String name, final String value) {
    this.locker.lock();
    try {
      if (value == null) {
        this.attributes.remove(name);
      }
      else {
        this.attributes.put(name, value);
      }
    }
    finally {
      this.locker.unlock();
    }
  }

  public void resetPayload() {
    this.locker.lock();
    try {
      if (this.mainTopic != null) {
        resetPayload(this.mainTopic);
      }
    }
    finally {
      this.locker.unlock();
    }
  }

  private void resetPayload(final MindMapTopic t) {
    t.setPayload(null);
    for (final MindMapTopic m : t.getChildren()) {
      resetPayload(m);
    }
  }

  public MindMapTopic getRoot() {
    this.locker.lock();
    try {
      return this.mainTopic;
    }
    finally {
      this.locker.unlock();
    }
  }

  static boolean fillMapByAttributes(final String line, final Map<String, String> map) {
    final Matcher attrmatcher = PATTERN_ATTRIBUTES.matcher(line);
    if (attrmatcher.find()) {
      final Matcher attrParser = PATTERN_ATTRIBUTE.matcher(attrmatcher.group(1));
      while (attrParser.find()) {
        map.put(attrParser.group(1), Utils.unescapeStr(attrParser.group(2)));
      }
      return true;
    }
    return false;
  }

  static String allAttributesAsString(final Map<String, String> map) {
    final StringBuilder buffer = new StringBuilder();

    boolean nonfirst = false;
    for (final Map.Entry<String, String> e : map.entrySet()) {
      if (nonfirst) {
        buffer.append(',');
      }
      else {
        nonfirst = true;
      }
      buffer.append(e.getKey()).append("=\"").append(Utils.escapeStr(e.getValue())).append('\"');
    }

    return buffer.toString();
  }

  public void write(final Writer out) throws IOException {
    this.locker.lock();
    try {
      out.append("Mind Map generated by NB MindMap plugin").append(NEXT_PARAGRAPH);
      if (!this.attributes.isEmpty()) {
        out.append("> ").append(MindMap.allAttributesAsString(this.attributes)).append(NEXT_LINE);
      }
      out.append("---").append(NEXT_LINE);
      this.mainTopic.write(out);
    }
    finally {
      this.locker.unlock();
    }
  }

  public void lock() {
    this.locker.lock();
  }

  public void unlock() {
    this.locker.unlock();
  }
}
