package com.igormaznitsa.mindmap.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Repeatable;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation allows provide information about target MMD file to collect data.
 *
 * @see MmdFiles
 */
@Repeatable(MmdFiles.class)
@Retention(RetentionPolicy.SOURCE)
@Target({ElementType.TYPE, ElementType.ANNOTATION_TYPE})
public @interface MmdFile {
  /**
   * Owner class folder.
   */
  String MACROS_SRC_CLASS_FOLDER = "${mmd.src.class.folder}";

  /**
   * File UID, it should be used in another MMD annotations to mark them as belonged to the file.
   *
   * @return file UID, if empty then will be autogenerated
   * @see MmdTopic#mmdFileUid()
   */
  String uid() default "";

  /**
   * Folder to generate the file.
   */
  String folder() default MACROS_SRC_CLASS_FOLDER;

  /**
   * File name, may include path part.
   *
   * @return file name, if empty then will use a class name based autogenerated one.
   * @see #folder()
   */
  String fileName() default "";

  /**
   * Root topic for the file.
   *
   * @return the root topic parameters for the file.
   */
  MmdTopic rootTopic() default @MmdTopic;
}
