#!/bin/sh
BASEDIR=`dirname "$0"`

if [ -z "$JAVA_HOME" ]; then
    JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
    if [ -d "$JAVA_HOME" ]; then export JAVA_HOME; fi
fi

exec java -Xmx2G -Djava.util.logging.config.file="$BASEDIR"/logger.properties -jar "$BASEDIR"/scia-reto-*.jar
