package com.igormaznitsa.mindmap.model.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Repeatable;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation allows provide information about target MMD file to collect data.
 *
 * @see MmdFiles
 */
@Repeatable(MmdFiles.class)
@Retention(RetentionPolicy.SOURCE)
@Target({
    ElementType.TYPE
})
public @interface MmdFile {
  /**
   * Owner class folder.
   */
  String MACROS_SRC_CLASS_FOLDER = "${mmd.src.class.folder}";

  /**
   * File UID, it should be used in another MMD annotations to mark them as belonged to the file.
   *
   * @return file UID, if empty then will be autogenerated
   * @see MmdTopic#mmdFileUid()
   */
  String uid() default "";

  /**
   * File name, may include relative path
   *
   * @return file name, if empty then will use a class name based autogenerated one.
   * @see #path()
   */
  String name() default "";

  /**
   * Path to place the MMD file. By default file will be placed in same source folder as owner class.
   *
   * @return path where file can be placed, by default in same source folder as containing class.
   * @see #MACROS_SRC_CLASS_FOLDER
   */
  String path() default MACROS_SRC_CLASS_FOLDER;
}
