package com.igormaznitsa.mindmap.model.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation allows provide information about target MMD file to collect data.
 */
@Retention(RetentionPolicy.SOURCE)
@Target({
    ElementType.TYPE
})
public @interface MmdFile {
  /**
   * Base folder for MMD files.
   */
  String MACROS_BASE_FOLDER = "${mmd.base.folder}";
  /**
   * Owner class folder.
   */
  String MACROS_CLASS_FOLDER = "${mmd.class.folder}";

  /**
   * File UID, it should be used in another MMD annotations to mark them as belonged to the file.
   *
   * @return file UID, if empty then will be autogenerated
   * @see MmdTopic#mmdFileUid()
   */
  String uid() default "";

  /**
   * File name, can include path.
   *
   * @return file name, if empty then will be autogenerated.
   */
  String name() default "";

  /**
   * Path to place the MMD file. By default file will be placed in same source folder as owner class.
   *
   * @return path where file can be placed, by default in same source folder as containing class.
   * @see #MACROS_BASE_FOLDER
   * @see #MACROS_CLASS_FOLDER
   */
  String path() default MACROS_CLASS_FOLDER;
}
