package com.igormaznitsa.mindmap.model.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation allows provide information about target MMD file to collect data.
 */
@Retention(RetentionPolicy.SOURCE)
@Target({
    ElementType.TYPE
})
public @interface MmdFile {
  /**
   * File UID, it should be used in another MMD annotations to mark them as belonged to the file.
   *
   * @return file UID, if empty then will be autogenerated
   * @see MmdTopic#mmdFileUid()
   */
  String uid() default "";

  /**
   * File name, can include path.
   *
   * @return file name, if empty then will be autogenerated.
   */
  String name() default "";
}
