#!/bin/sh
BASEDIR=`dirname "$0"`

exec "$BASEDIR"/jre/bin/java -Xmx2G --add-opens java.desktop/com.apple.eawt=ALL-UNNAMED -Djava.util.logging.config.file="$BASEDIR"/logger.properties -jar "$BASEDIR"/scia-reto-*.jar
